apiVersion: apps/v1
kind: Deployment
metadata:
 name: zomato
spec:
 replicas: 2
 selector:
    matchLabels:
     name: "zomato"
 template:
  metadata:
    labels:
      name: "zomato"
  spec:
    containers:
     - name: zomatoimage
       image: vijaysai1718/zomato:latest
       ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: serviceforzomato
spec:
 selector:
  name: "zomato"
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
